version: 1.0.{build}
image:
- Visual Studio 2017
- Ubuntu1804
install:
- cmd: cinst innosetup
- sh: sudo apt-get -y update && sudo apt-get install -y libcurl4-openssl-dev pkg-config libtbb-dev libasound2-dev libgtk-3-dev libwebkit2gtk-4.0-dev libglew-dev libjack-dev
- git submodule update --init --recursive
environment:
  matrix:
  - {}
build_script:
- cmd: >-
    buildWindows.bat
- sh: >-
    cd third_party/flatbuffers &&
    cmake -S . -B LinuxBuilds &&
    cmake --build LinuxBuilds &&
    cd ../.. &&
    cmake -S . -B builds &&
    cmake --build builds
    